### ISSUE TITLE
Javascript Object Abstraction

### ISSUE THREAD

**Issue by isaacguerreir** [NectarJS/jnom#1]
# Javascript Object Abstraction

To create a Javascript Native Object Model in the target languages first, we need to determine all the aspects of the Javascript Object. Here are some visible aspects of an `Object`:

## Syntax

```
  // Objects can be initialiser using the brackets {}
{ [ nameValuePair1[, nameValuePair2[, ...nameValuePairN] ] ] }

  // Objects can be initialiser using a constructor
  new Object([value])
```

### Parameters
_**nameValuePair1, nameValuePair2, ... nameValuePairN**_
Pairs of values, each one separated by a colon.

_**value**_
Any value.

### Properties of a `Object`:

_**Object.length**_
_**Object.prototype**_

### Methods of a `Object`:

_**Object.assign()**_
_**Object.create()**_
_**Object.defineProperty()**_
_**Object.defineProperties()**_
_**Object.entries()**_
_**Object.freeze()**_
_**Object.getOwnPropertyDescriptor()**_
_**Object.getOwnPropertyDescriptors()**_
_**Object.getOwnPropertyNames()**_
_**Object.getOwnPropertySymbols()**_
_**Object.getPrototypeOf()**_
_**Object.is()**_
_**Object.isExtensible()**_
_**Object.isFrozen()**_
_**Object.isSealed()**_
_**Object.keys()**_
_**Object.preventExtensions()**_
_**Object.seal()**_
_**Object.setPrototypeOf()**_
_**Object.values()**_

## `Object` prototype
All objects inherit methods and properties from `Object.prototype`.

### Properties:
_**Object.prototype.constructor**_
_**Object.prototype.`__proto__`**_
_**Object.prototype.__noSuchMethod__ **_

###  Methods:

_**Object.prototype.__defineGetter__()**_
_**Object.prototype.__defineSetter__()**_
_**Object.prototype.__lookupGetter__()**_
_**Object.prototype.__lookupSetter__()**_
_**Object.prototype.hasOwnProperty()**_
_**Object.prototype.isPrototypeOf()**_
_**Object.prototype.propertyIsEnumerable()**_
_**Object.prototype.toSource()**_
_**Object.prototype.toLocaleString()**_
_**Object.prototype.toString()**_
_**Object.prototype.unwatch()**_
_**Object.prototype.valueOf()**_
_**Object.prototype.watch()**_

# More information

This is a simple sketch of what are the Javascript Object. Please improve our document with more specfications! Only write your contribution here.

#References: 

[ECMAScript® Language Specification](https://www.ecma-international.org/ecma-262/5.1/index.html)
[Object Documentation - MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object)

**Comment by adrien-thierry** [comment]
Added joa.MD
